### ISSUE TITLE
FreeBSD and Gentoo logos are squashed on front page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/cloud-init.io#50]
1\. Go to https://cloud-init.io/.
2\. Scroll to the FreeBSD and Gentoo logos.

What you see: They’re squashed.

![cloud-init-os-logos](https://cloud.githubusercontent.com/assets/19801137/26308375/e2014dc0-3ef0-11e7-8180-444f802c650e.png)

What you should see: They aren’t squashed.

**Comment by powersj** [comment]
Running on Ubuntu 17.04 (Zesty), in Chrome (59.0.3071.86-1) I do not see this, but I do see this in Firefox (53.0.3+build1-0ubuntu0.17.04.2).

**Comment by pmahnke** [comment]
@anthonydillon and @matthewpaulthomas this appears fixed? can I close the issue?

**Comment by anthonydillon** [comment]
Sorry I forget to come back and close this when the branch landed.
