### ISSUE TITLE
Text is not aligned down page

### ISSUE THREAD

**Issue by powersj** [canonical-websites/cloud-init.io#66]
## Summary

The text at the top of the page uses a column width of 8.
The text in the next section uses a column width of 9.
The rest of the page uses a column width of 12.

This appears very off and looks very awkward. Should these all be aligned to 12?

## Process

Search for "col-8" and "col-9"

## Current and expected result

The text should look more aligned and consistent

## Screenshot
![image](https://user-images.githubusercontent.com/6453401/28681073-12dd7280-72ad-11e7-86be-aada4856d2dd.png)

**Comment by anthonydillon** [comment]
@joanasa89 @kwm14 @spencerbygraves Could one of you take a look and suggest a solution.

**Comment by spencerbygraves** [comment]
@anthonydillon can we align all text to 8 col, so the line length is equal and not too long. Can we also move the right hand two bullets to the left. Thanks.
