### ISSUE TITLE
Wrong Git logo

### ISSUE THREAD

**Issue by rcunning02** [canonical-websites/cloud-init.io#68]
## Summary

The logo between the headings "Source code" and "Git" (as seen on an iPod touch) appears to be for Bazaar and not for Git.

## Current and expected result

Suggested replacement: <http://git-scm.com/images/logos/downloads/Git-Icon-1788C.png>

## Screenshot

I cannot add a screenshot with the GitHub mobile frontend.

**Comment by pmahnke** [comment]
@rcunning02 thanks for filing the issues... should go live soon
